spring.application.name=Pi_back
server.port=8090
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/my_CrediGuard?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.main.allow-bean-definition-overriding=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

### CORS ###
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*

### JWT ###
app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_123456
app.jwt.expiration-ms=86400000

### BOOTSTRAP ADMIN ###
app.bootstrap.admin.email=admin@crediguard.local
app.bootstrap.admin.password=Admin123!
app.bootstrap.admin.full-name=Default Admin